version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - erunion
      - kanadgupta
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps-gha)
      prefix-development: chore(deps-gha-dev)

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
      - kanadgupta
    labels:
      - dependencies
    groups:
      minor-development-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      # See https://github.com/sindresorhus/ora/issues/229
      - dependency-name: ora
        versions:
          - '>= 7'
