name: rdme
author: ReadMe
branding:
  color: blue
  icon: book-open
description: 'Update your ReadMe developer hubs in a CI environment.'
inputs:
  rdme:
    description: 'String containin command and arguments to pass into rdme'
    required: true
runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install rdme deps
      run: cd ${{ github.action_path }} && npm install --production --quiet
      shell: bash
    - run: ${{ github.action_path }}/bin/rdme ${{ inputs.rdme }}
      shell: bash
