name: rdme 🦉 Sync to ReadMe
author: ReadMe
branding:
  color: blue
  icon: book-open
description: Sync OpenAPI/Swagger (OAS) definitions and Markdown documentation from your GitHub repository to your ReadMe developer hub
inputs:
  rdme:
    description: Command to pass into rdme
    required: true
runs:
  using: docker
  image: Dockerfile
