name: rdme
author: ReadMe
branding:
  color: blue
  icon: book-open
inputs:
  rdme:
    description: String containing command and arguments to pass into rdme
    required: true
runs:
  using: "composite"
  steps:
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install rdme deps
      run: npm install --production --silent
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: bin/rdme ${{ inputs.rdme }}
      shell: bash
      working-directory: ${{ github.action_path }}
