name: rdme 🦉 Sync to ReadMe
author: ReadMe
branding:
  color: blue
  icon: book-open
description: Sync OpenAPI/Swagger (OAS) definitions and Markdown documentation from your GitHub repository to your ReadMe developer hub
inputs:
  rdme:
    description: Command to pass into rdme
    required: true
outputs:
  rdme:
    description: The rdme command result output
runs:
  using: docker
  image: docker://ghcr.io/readmeio/rdme:8.6.6
  args:
    - docker-gha
    - ${{ inputs.rdme }}
