/**
 * The base GitHub Action workflow file, which is used for generating the YAML file.
 *
 * The reason this is expressed as a JavaScript string as opposed to a YAML file is because
 * TypeScript doesn't have a great way to copy over non-TS files, and this way we can write internal
 * comments like this!
 *
 * @see {@link https://github.com/microsoft/TypeScript/issues/30835}
 */
const yamlBase = `# This GitHub Action workflow was auto-generated by the \`rdme\` cli on :[](timestamp)
# You can view our full documentation here: https://docs.readme.com/docs/rdme
name: ReadMe GitHub Action 🦉

on:
  push:
    branches:
      # This workflow will run every time you push code to the following branch: \`:[](branch)\`
      # Check out GitHub's docs for more info on configuring this:
      # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows
      - :[](branch)

jobs:
  rdme-:[](command):
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run \`:[](command)\` command 🚀
        uses: readmeio/rdme@:[](rdmeVersion)
        with:
          rdme: :[](commandString)
`;

export default yamlBase;
