name: GitHub Action Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Run GitHub Action command test
        uses: ./
        with:
          command: 'validate __tests__/__fixtures__/ref-oas/petstore.json'
